// //table user
// //fields Id, name , email

// List<AggregateResult> users = [SELECT Count(ID) ids, Email from User];

// for(Aggregateresult ar : users)
// {

// }

// Given an array of random positive numbers and positive size `k`, find
// the maximum sum of any contiguous sub-array of size `k`.
// ## Examples

// ### Example 1
// **Input**
// Array: [1, 3, 2, 5, 1, 6]
// k: 2
// **Output**: 7
// **Explanation**: sub array [1, 6] of size 2 sums up to 7

public Integer  ReturnMaximum(List<Integer> arr, Integer size)
{
    for(integer i = 0 ; i < arr.size(); i++)
    {
        integer first = arr[i]
        {
            for(integer j = i+1 ; j< arr.size(); j++)
            {
                
            }
        }
    }
}

